<?php
$data = array (
  0 => 
  array (
    'cat_id' => '1',
    'cat_name' => '系统分类',
    'cat_type' => '2',
    'keywords' => '',
    'cat_desc' => '系统保留分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '2',
    'aricle_num' => '0',
  ),
  1 => 
  array (
    'cat_id' => '6',
    'cat_name' => '凡客新闻',
    'cat_type' => '1',
    'keywords' => '凡客新闻',
    'cat_desc' => '凡客新闻',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  2 => 
  array (
    'cat_id' => '7',
    'cat_name' => '今日聚焦',
    'cat_type' => '1',
    'keywords' => '今日聚焦',
    'cat_desc' => '今日聚焦',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '0',
    'has_children' => '0',
    'aricle_num' => '0',
  ),
  3 => 
  array (
    'cat_id' => '2',
    'cat_name' => '网店信息',
    'cat_type' => '3',
    'keywords' => '',
    'cat_desc' => '网店信息分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '0',
    'aricle_num' => '6',
  ),
  4 => 
  array (
    'cat_id' => '3',
    'cat_name' => '网店帮助分类',
    'cat_type' => '4',
    'keywords' => '',
    'cat_desc' => '网店帮助分类',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '1',
    'has_children' => '6',
    'aricle_num' => '0',
  ),
  5 => 
  array (
    'cat_id' => '4',
    'cat_name' => '新手指南',
    'cat_type' => '5',
    'keywords' => '新手指南',
    'cat_desc' => '新手指南',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  6 => 
  array (
    'cat_id' => '8',
    'cat_name' => '配送方式',
    'cat_type' => '5',
    'keywords' => '配送方式',
    'cat_desc' => '配送方式',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  7 => 
  array (
    'cat_id' => '9',
    'cat_name' => '售后服务',
    'cat_type' => '5',
    'keywords' => '售后服务',
    'cat_desc' => '售后服务',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '2',
  ),
  8 => 
  array (
    'cat_id' => '10',
    'cat_name' => '帮助中心',
    'cat_type' => '5',
    'keywords' => '帮助中心',
    'cat_desc' => '帮助中心',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  9 => 
  array (
    'cat_id' => '11',
    'cat_name' => '会员中心',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '50',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
  10 => 
  array (
    'cat_id' => '5',
    'cat_name' => '如何付款/退款',
    'cat_type' => '5',
    'keywords' => '',
    'cat_desc' => '',
    'sort_order' => '60',
    'show_in_nav' => '0',
    'parent_id' => '3',
    'has_children' => '0',
    'aricle_num' => '3',
  ),
);
?>