<?php
$data = array (
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '男装',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '10',
    'has_children' => '5',
    'goods_num' => '10',
    'level' => 0,
    'id' => '1',
    'name' => '男装',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '5',
    'name' => '衬衫',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '休闲衬衫',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '8',
    'name' => '休闲衬衫',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '情侣衬衫',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '9',
    'name' => '情侣衬衫',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '牛津纺衬衫',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '6',
    'name' => '牛津纺衬衫',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '短袖衬衫',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '10',
    'name' => '短袖衬衫',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '商务衬衫',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '7',
    'name' => '商务衬衫',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => 'POLO衫＆T恤',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => 'POLO衫＆T恤',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '短袖T恤',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '17',
    'name' => '短袖T恤',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '短袖POLO衫',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '15',
    'name' => '短袖POLO衫',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '长袖POLO衫',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '16',
    'name' => '长袖POLO衫',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '裤子',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '裤子',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '西裤',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '18',
    'name' => '西裤',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '休闲裤',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '19',
    'name' => '休闲裤',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '牛仔裤',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '20',
    'name' => '牛仔裤',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '针织衫',
    'measure_unit' => '件',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '11',
    'name' => '针织衫',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '针织背心',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '21',
    'name' => '针织背心',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '长袖针织衫',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '22',
    'name' => '长袖针织衫',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '外套',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '12',
    'name' => '外套',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '西服',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '24',
    'name' => '西服',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '卫衣',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '25',
    'name' => '卫衣',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '夹克',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '23',
    'name' => '夹克',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '女装',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '20',
    'has_children' => '4',
    'goods_num' => '2',
    'level' => 0,
    'id' => '2',
    'name' => '女装',
  ),
  33 => 
  array (
    'cat_id' => '33',
    'cat_name' => '外套',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 1,
    'id' => '33',
    'name' => '外套',
  ),
  40 => 
  array (
    'cat_id' => '40',
    'cat_name' => '大衣',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '40',
    'name' => '大衣',
  ),
  37 => 
  array (
    'cat_id' => '37',
    'cat_name' => '西服',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '37',
    'name' => '西服',
  ),
  34 => 
  array (
    'cat_id' => '34',
    'cat_name' => '卫衣',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '34',
    'name' => '卫衣',
  ),
  38 => 
  array (
    'cat_id' => '38',
    'cat_name' => '风衣',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '38',
    'name' => '风衣',
  ),
  39 => 
  array (
    'cat_id' => '39',
    'cat_name' => '羽绒服',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '39',
    'name' => '羽绒服',
  ),
  36 => 
  array (
    'cat_id' => '36',
    'cat_name' => '夹克',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '36',
    'name' => '夹克',
  ),
  30 => 
  array (
    'cat_id' => '30',
    'cat_name' => '针织衫',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '2',
    'level' => 1,
    'id' => '30',
    'name' => '针织衫',
  ),
  31 => 
  array (
    'cat_id' => '31',
    'cat_name' => '长袖针织衫',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '31',
    'name' => '长袖针织衫',
  ),
  32 => 
  array (
    'cat_id' => '32',
    'cat_name' => '短袖针织衫',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '32',
    'name' => '短袖针织衫',
  ),
  41 => 
  array (
    'cat_id' => '41',
    'cat_name' => 'POLO衫＆T恤',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '41',
    'name' => 'POLO衫＆T恤',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '短袖POLO衫',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '43',
    'name' => '短袖POLO衫',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '26',
    'name' => '衬衫',
  ),
  27 => 
  array (
    'cat_id' => '27',
    'cat_name' => '长袖衬衫',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '27',
    'name' => '长袖衬衫',
  ),
  28 => 
  array (
    'cat_id' => '28',
    'cat_name' => '短袖衬衫',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '28',
    'name' => '短袖衬衫',
  ),
  29 => 
  array (
    'cat_id' => '29',
    'cat_name' => '情侣衬衫',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '29',
    'name' => '情侣衬衫',
  ),
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '童装',
    'measure_unit' => '件',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '5',
    'sort_order' => '30',
    'has_children' => '7',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '童装',
  ),
  62 => 
  array (
    'cat_id' => '62',
    'cat_name' => '裙子',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '62',
    'name' => '裙子',
  ),
  57 => 
  array (
    'cat_id' => '57',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '57',
    'name' => '衬衫',
  ),
  54 => 
  array (
    'cat_id' => '54',
    'cat_name' => '婴儿装',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '54',
    'name' => '婴儿装',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '针织衫',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '59',
    'name' => '针织衫',
  ),
  85 => 
  array (
    'cat_id' => '85',
    'cat_name' => '针织背心',
    'measure_unit' => '',
    'parent_id' => '59',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '85',
    'name' => '针织背心',
  ),
  55 => 
  array (
    'cat_id' => '55',
    'cat_name' => 'POLO衫',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '55',
    'name' => 'POLO衫',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '外套',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '60',
    'name' => '外套',
  ),
  56 => 
  array (
    'cat_id' => '56',
    'cat_name' => 'T恤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '56',
    'name' => 'T恤',
  ),
  75 => 
  array (
    'cat_id' => '75',
    'cat_name' => '长袖T恤',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '75',
    'name' => '长袖T恤',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '短袖 T恤',
    'measure_unit' => '',
    'parent_id' => '56',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '79',
    'name' => '短袖 T恤',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '鞋',
    'measure_unit' => '对',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '5',
    'sort_order' => '40',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '鞋',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '男鞋',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '95',
    'name' => '男鞋',
  ),
  103 => 
  array (
    'cat_id' => '103',
    'cat_name' => '正装皮鞋',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '103',
    'name' => '正装皮鞋',
  ),
  104 => 
  array (
    'cat_id' => '104',
    'cat_name' => '系带',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '104',
    'name' => '系带',
  ),
  97 => 
  array (
    'cat_id' => '97',
    'cat_name' => '男帆布鞋',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '97',
    'name' => '男帆布鞋',
  ),
  102 => 
  array (
    'cat_id' => '102',
    'cat_name' => '男运动休闲鞋',
    'measure_unit' => '',
    'parent_id' => '95',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '102',
    'name' => '男运动休闲鞋',
  ),
  35 => 
  array (
    'cat_id' => '35',
    'cat_name' => '马甲',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '35',
    'name' => '马甲',
  ),
);
?>